### ISSUE TITLE
./scripts/getver.sh returns 'unknown'

### ISSUE THREAD

**Issue by nxhack** [lede-project/staging#20]
In case of  cloning github repository, getver.sh returns error.

```
$ ./scripts/getver.sh 
fatal: No names found, cannot describe anything.
unknown
```

**Comment by NeoRaider** [comment]
Huh, the github repo is missing the *reboot* tag. We've already noticed that the same happens when you make a shallow clone of the main repo.

I'm not sure if we can do anything better than return `unknown` if the tag is missing, but maybe we can figure something out. At least, we should mirror all tags into the github repo.

**Comment by NeoRaider** [comment]
I've added the *reboot* tag to the staging repo, a `git pull` or `git fetch --tags` should fix your issue unless your clone is shallow.

**Comment by nxhack** [comment]
Thx! It work.

```
$ git pull
remote: Counting objects: 1, done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), done.
From https://github.com/lede-project/staging
 * [new tag]         reboot     -> reboot
Already up-to-date.
$ ./scripts/getver.sh 
r269

```
