### ISSUE TITLE
`mount_root` not working in failsafe

### ISSUE THREAD

**Issue by VittGam** [lede-project/staging#8]
Hello,

The `mount_root` command does nothing in failsafe mode. The root is not mounted.

Cheers,
Vittorio

**Comment by NeoRaider** [comment]
The issue seems to be that the PREINIT variable is not set in the environment provided by dropbear. Has something changed here lately, or is this broken since the switch from telnet to dropbear?

As a workaround, `PREINIT=1 mount_root` can be used. In any case, it might make sense for *mount_root* to actually check if the root is already mounted instead of relying on such a variable.

**Comment by VittGam** [comment]
This should be the cause then, as if I remember well the environment an SSH server presents to the shell is a subset of the _SSH client_ environment, not of the SSH server parent environment.

**Comment by blogic** [comment]
@NeoRaider: agreed, we should add a "is_root_mounted()". i have added this on my todo list

**Comment by blogic** [comment]
added a fix in the fstools tree and added a patch in my staging tree to fix the regression.
